# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      # Validate
      - /gitlab-templates/clang-format.yml
      - /gitlab-templates/qml-lint.yml
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/xml-lint.yml
      - /gitlab-templates/yaml-lint.yml
      # Build and Test
      - /gitlab-templates/alpine-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/linux-qt6-next.yml
      # Package
      - /gitlab-templates/flatpak.yml
